#!/bin/bash

## Author: Tristan Werden
## Version: 1.0

IFS=","

declare inFile="$1"
declare -a lastNames
declare -a firstNames
declare -a ages

main() {
    readFile
    countOldPeople
}

readFile() {
    declare -i lineNumber=0
    while read lastName firstName age
    do
        lastNames[$lineNumber]=$lastName
        firstNames[$lineNumber]=$firstName
        ages[$lineNumber]=$age
        (( lineNumber++ ))
    done < $inFile    
}

countOldPeople(){
    declare -i oldCount=0

    for (( i=0; i < ${#ages[@]}; i++ ))
    do
        if [ ${ages[i]} -gt 61 ] ##magic number I know, but... it works lol
        then
            (( oldCount++ ))
        fi
    done

    echo $oldCount
}


main
